# Generated by Django 5.0.4 on 2024-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
